ToDoList/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("todos/", include("to_do_list_app.urls"))
]

to_do_list_app/urls.py
from django.urls import path
from . import views

app_name = "to_do_list"
urlpatterns = [
    path("", views.index, name = "index"),
    path("new", views.create, name = "create"),
    path("check/<int:item_index>", views.check, name = "check")
]

to_do_list_app/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Item(models.Model):
    content = models.CharField(max_length = 255)
    is_done = models.BooleanField(default = False)
    created = models.DateTimeField(default = timezone.now())
    def __str__(self):
        return self.content

to_do_list_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Item

# Create your views here.
def index(request):
    items = Item.objects.all()
    return render(request, "./index.html", {
        "items": items
    })

def create(request):
    user_input = request.POST["content"]
    if not (user_input == ""):
        new_item = Item(content = user_input)
        new_item.save()
    return HttpResponseRedirect(reverse("to_do_list:index"))

def check(request, item_index):
    checked_item = Item.objects.get(id = item_index)
    checked_item.is_done = True
    checked_item.save()
    return HttpResponseRedirect(reverse("to_do_list:index"))

to_do_list_app/templates/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To Do List App</title>
</head>
<body>
    <h1>To Do List with Django</h1>
    <form action="{% url 'to_do_list:create' %}" method="POST">
        {% csrf_token %}
        <label for="content">Content: </label>
        <input type="text" name="content" id="content" placeholder="Enter a new To-Do...">
        <button type="submit">Submit!</button>
    </form>
    {% if items %}
    <ul>
        {% for item in items %}
        <li>
            {% if item.is_done %}
            <del>{{ item.content }}</del>
            {% else %}
            <p>{{ item.content }}<a href="{% url 'to_do_list:check' item.id %}">Check</a></p>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No items yet.</p>
    {% endif %}
</body>
</html>